// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFileMerge() {
  return window['go']['main']['App']['CancelFileMerge']();
}

export function CancelSheetMerge() {
  return window['go']['main']['App']['CancelSheetMerge']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClassifyPaths(arg1) {
  return window['go']['main']['App']['ClassifyPaths'](arg1);
}

export function DirWritable(arg1) {
  return window['go']['main']['App']['DirWritable'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListSheets(arg1) {
  return window['go']['main']['App']['ListSheets'](arg1);
}

export function MergeFiles(arg1) {
  return window['go']['main']['App']['MergeFiles'](arg1);
}

export function MergeSheets(arg1) {
  return window['go']['main']['App']['MergeSheets'](arg1);
}

export function PickExcelFile() {
  return window['go']['main']['App']['PickExcelFile']();
}

export function PickExcelFiles() {
  return window['go']['main']['App']['PickExcelFiles']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReportDemo() {
  return window['go']['main']['App']['ReportDemo']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectFolderAndScan() {
  return window['go']['main']['App']['SelectFolderAndScan']();
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
