// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function CancelFileMerge():Promise<boolean>;

export function CancelSheetMerge():Promise<boolean>;

export function CheckForUpdates():Promise<model.UpdateCheckResult>;

export function ClassifyPaths(arg1:Array<string>):Promise<Array<model.FileRef>>;

export function DirWritable(arg1:string):Promise<boolean>;

export function GetAppInfo():Promise<model.AppInfo>;

export function GetSettings():Promise<model.Settings>;

export function Health():Promise<Record<string, string>>;

export function ListSheets(arg1:string):Promise<model.SheetListResult>;

export function MergeFiles(arg1:main.MergeFilesRequest):Promise<model.MergeResult>;

export function MergeSheets(arg1:main.MergeSheetsRequest):Promise<model.MergeResult>;

export function PickExcelFile():Promise<model.FileRef>;

export function PickExcelFiles():Promise<Array<model.FileRef>>;

export function PickFolder():Promise<string>;

export function Ping():Promise<string>;

export function ReportDemo():Promise<model.MergeResult>;

export function ResetSettings():Promise<model.Settings>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function ScanFolder(arg1:string):Promise<Array<model.FileRef>>;

export function SelectFolderAndScan():Promise<Array<model.FileRef>>;

export function SetSettings(arg1:model.Settings):Promise<model.Settings>;
